OdroidC2 enabled USB_MASS_STORAGE
Raybuntu/LibreELEC.tv pull request #45
Opened 2017-11-18 22:09 UTC by danielfmo

as requested here: https://github.com/Raybuntu/LibreELEC.tv/issues/44

2017-11-19 08:23 UTC, Ray-future approved these changes
Thanks I will test if it builds and then merge it. This change should be upstreamed to LibreELEC too.

2017-11-20 07:43 UTC, Ray-future requested changes

2017-11-20 07:43 UTC, Raybuntu commented on projects/Odroid_C2/linux/linux.aarch64.conf
> +USB_MASS_STORAGE=y
It has to be CONFIG_USB_MASS_STORAGE not USB_MASS_STORAGE ;)

2017-11-20 11:43 UTC, Raybuntu commented
@danielfmo I've tested this PR but unfortunately it requires some additional config changes. I'm not sure what additionally is required to solve issue #44 .
So can you please go through the config changes and then add those too to this PR?

2017-11-20 12:11 UTC, danielfmo commented
@mkmt: as stated by Raybuntu, those configurations are not enough, can you please add what is missing? 
Or at lease share some sources.

2017-11-20 12:20 UTC, mkmt commented
USB_MASS_STORAGE must be set as a module (all configuration is done while loading module),

dependencies for this module are:
USB_SUPPORT (already done)
USB_GADGET (already done)
BLOCK (already done)

missing:
USB_CONFIGFS (think as a module as well)
USB_GADGETFS (think as a module as well)
USB_MASS_STORAGE (as a module)

2017-11-20 13:47 UTC, Raybuntu commented
This is what I have when using oldconfig: http://sprunge.us/LjCR

2018-03-09 09:59 UTC, Raybuntu commented
Odroid C2 was moved to the Amlogic project in LibreELEC. I suggest you send your PR to official LE.

2018-03-09 09:59 UTC, closed without merging